spring: 
  datasource:
    url: jdbc:h2:mem:usersdb
  cloud:
    discovery: 
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true

